### ISSUE TITLE
Add a label?

### ISSUE THREAD

**Issue by CheckeredFlag** [jg23497/Header-Inject#2]
Any chance you can add a label field?  This can be a helpful reminder for the purpose of an item.

**Comment by jg23497** [comment]
Hi @CheckeredFlag,

Thanks for the feedback. I agree, this would be a useful addition as not all HTTP header names and values are self-explanatory.

The Chrome extension manifest file needs to be updated to the v3 format fairly soon due to Google's policy changes, so will see if this change can be included in the bundle.

**Comment by jg23497** [comment]
Draft PR raised: #3.

**Comment by jg23497** [comment]
PR merged and Header Inject v1.1.0 submitted to the Chrome Web Store for review. Will close this issue once v1.1.0 is published by Google.

**Comment by jg23497** [comment]
v1.1.0 is now live. Closing issue.

**Comment by CheckeredFlag** [comment]
Many thanks!
